import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
django.setup()

from django.contrib.auth.models import User
from quizzes.models import Quiz, question, choice

# Get or create a superuser for created_by
user, created = User.objects.get_or_create(
    username="admin", defaults={"is_superuser": True, "is_staff": True}
)
if created:
    user.set_password("admin123")
    user.save()

# Create the JavaScript Job Test quiz
js_job_quiz, created = Quiz.objects.get_or_create(
    title="JavaScript Job Test",
    defaults={
        "description": "A comprehensive JavaScript quiz for job preparation with 60 questions across Beginner, Intermediate, and Advanced levels.",
        "created_by": user,
        "is_active": True,
        "is_special": True,
    },
)
print(f"Quiz created: {js_job_quiz.title}")

# Questions data
questions_data = [
    # Beginner (20 questions)
    (
        "JavaScript is a:",
        "Programming language",
        "Database",
        "Operating System",
        "Compiler",
        1,
        "Beginner",
    ),
    (
        "Which company developed JavaScript?",
        "Microsoft",
        "Google",
        "Netscape",
        "Oracle",
        3,
        "Beginner",
    ),
    (
        "Which keyword declares block-scoped variable?",
        "var",
        "let",
        "constant",
        "static",
        2,
        "Beginner",
    ),
    (
        "Which operator is strict equality?",
        "==",
        "=",
        "===",
        "!=",
        3,
        "Beginner",
    ),
    (
        "Array index starts from:",
        "1",
        "0",
        "-1",
        "Depends",
        2,
        "Beginner",
    ),
    (
        "Which is used to print in console?",
        "echo",
        "print",
        "console.log",
        "log.print",
        3,
        "Beginner",
    ),
    (
        "Which symbol is used for comments?",
        "#",
        "//",
        "<!--",
        "--",
        2,
        "Beginner",
    ),
    (
        "typeof null returns:",
        "null",
        "object",
        "undefined",
        "string",
        2,
        "Beginner",
    ),
    (
        "Which data type is NOT primitive?",
        "string",
        "number",
        "boolean",
        "object",
        4,
        "Beginner",
    ),
    (
        "Which loop checks condition first?",
        "do-while",
        "for",
        "while",
        "loop",
        3,
        "Beginner",
    ),
    (
        "Which keyword defines constant?",
        "var",
        "let",
        "const",
        "static",
        3,
        "Beginner",
    ),
    (
        "NaN stands for:",
        "No assigned number",
        "Not a number",
        "Null and none",
        "New async number",
        2,
        "Beginner",
    ),
    (
        "Which method adds element to array end?",
        "push",
        "pop",
        "shift",
        "concat",
        1,
        "Beginner",
    ),
    (
        "Which removes last element?",
        "push",
        "pop",
        "shift",
        "unshift",
        2,
        "Beginner",
    ),
    (
        "JSON stands for:",
        "JavaScript Object Notation",
        "Java Source Object Network",
        "Java Syntax Object Notation",
        "None",
        1,
        "Beginner",
    ),
    (
        "Boolean values are:",
        "true/false",
        "yes/no",
        "1/0",
        "on/off",
        1,
        "Beginner",
    ),
    (
        "Which keyword defines function?",
        "func",
        "define",
        "function",
        "def",
        3,
        "Beginner",
    ),
    (
        "parseInt converts to:",
        "String",
        "Integer",
        "Boolean",
        "Object",
        2,
        "Beginner",
    ),
    (
        "Which operator is logical AND?",
        "||",
        "&&",
        "!",
        "&",
        2,
        "Beginner",
    ),
    (
        "DOM stands for:",
        "Document Object Model",
        "Data Object Mode",
        "Digital Output Model",
        "None",
        1,
        "Beginner",
    ),
    # Intermediate (20 questions)
    (
        "What is closure?",
        "Function with preserved scope",
        "Object",
        "Loop",
        "Array",
        1,
        "Intermediate",
    ),
    (
        "Arrow functions use:",
        "=>",
        "->",
        "==>",
        "<=",
        1,
        "Intermediate",
    ),
    (
        "Promise represents:",
        "Future value",
        "Loop",
        "Error",
        "Variable",
        1,
        "Intermediate",
    ),
    (
        "async/await is used for:",
        "Styling",
        "Asynchronous code",
        "Looping",
        "Objects",
        2,
        "Intermediate",
    ),
    (
        "Which method transforms array?",
        "map",
        "for",
        "if",
        "switch",
        1,
        "Intermediate",
    ),
    (
        "filter() returns:",
        "All elements",
        "Matching elements",
        "First element",
        "None",
        2,
        "Intermediate",
    ),
    (
        "reduce() reduces array to:",
        "Single value",
        "Array",
        "Object",
        "String",
        1,
        "Intermediate",
    ),
    (
        "Spread operator is:",
        "...",
        "***",
        "<<<",
        "///",
        1,
        "Intermediate",
    ),
    (
        "Destructuring extracts from:",
        "Array/Object",
        "Loop",
        "String",
        "Number",
        1,
        "Intermediate",
    ),
    (
        "this keyword refers to:",
        "Current context",
        "Window always",
        "Function only",
        "Parent",
        1,
        "Intermediate",
    ),
    (
        "Event delegation improves:",
        "Performance",
        "Memory leak",
        "Errors",
        "None",
        1,
        "Intermediate",
    ),
    (
        "setTimeout is:",
        "Blocking",
        "Non-blocking",
        "Synchronous",
        "Compiler",
        2,
        "Intermediate",
    ),
    (
        "Template literals use:",
        " ",
        "'",
        "``",
        "<>",
        3,
        "Intermediate",
    ),
    (
        "Which is ES6 feature?",
        "let",
        "var",
        "print",
        "echo",
        1,
        "Intermediate",
    ),
    (
        "Modules use:",
        "import/export",
        "include",
        "require only",
        "link",
        1,
        "Intermediate",
    ),
    (
        "Symbol is:",
        "Primitive type",
        "Object",
        "Loop",
        "Array",
        1,
        "Intermediate",
    ),
    (
        "Object.assign is used for:",
        "Copying objects",
        "Looping",
        "Deleting",
        "Parsing",
        1,
        "Intermediate",
    ),
    (
        "Default parameters introduced in:",
        "ES6",
        "ES5",
        "ES3",
        "ES2",
        1,
        "Intermediate",
    ),
    (
        "forEach returns:",
        "New array",
        "Nothing",
        "Boolean",
        "String",
        2,
        "Intermediate",
    ),
    (
        "JSON.parse converts to:",
        "String",
        "Object",
        "Number",
        "Boolean",
        2,
        "Intermediate",
    ),
    # Advanced (20 questions)
    (
        "Hoisting moves:",
        "Declarations to top",
        "Functions to bottom",
        "Loops",
        "None",
        1,
        "Advanced",
    ),
    (
        "Prototype is used for:",
        "Inheritance",
        "Looping",
        "DOM",
        "Error",
        1,
        "Advanced",
    ),
    (
        "IIFE stands for:",
        "Immediately Invoked Function Expression",
        "Internal Invoke Function",
        "None",
        "None",
        1,
        "Advanced",
    ),
    (
        "Event loop handles:",
        "Async callbacks",
        "DOM only",
        "Loops",
        "Classes",
        1,
        "Advanced",
    ),
    (
        "WeakMap allows:",
        "Garbage collected keys",
        "Strong references",
        "Arrays",
        "None",
        1,
        "Advanced",
    ),
    (
        "Debouncing limits:",
        "Frequent calls",
        "Memory",
        "Loops",
        "Variables",
        1,
        "Advanced",
    ),
    (
        "Throttling controls:",
        "Execution rate",
        "Memory usage",
        "Objects",
        "None",
        1,
        "Advanced",
    ),
    (
        "Object.freeze makes object:",
        "Immutable",
        "Deleted",
        "Looped",
        "String",
        1,
        "Advanced",
    ),
    (
        "call() changes:",
        "Context",
        "Object type",
        "Loop",
        "String",
        1,
        "Advanced",
    ),
    (
        "apply() differs by:",
        "Argument array",
        "Looping",
        "Scope",
        "None",
        1,
        "Advanced",
    ),
    (
        "bind() returns:",
        "New function",
        "Object",
        "String",
        "Loop",
        1,
        "Advanced",
    ),
    (
        "Microtasks include:",
        "Promises",
        "setTimeout",
        "DOM",
        "None",
        1,
        "Advanced",
    ),
    (
        "Generator defined using:",
        "function*",
        "yield only",
        "class",
        "loop",
        1,
        "Advanced",
    ),
    (
        "yield pauses:",
        "Generator",
        "Loop",
        "Class",
        "Object",
        1,
        "Advanced",
    ),
    (
        "Class inheritance uses:",
        "extends",
        "inherit",
        "superclass",
        "prototype",
        1,
        "Advanced",
    ),
    (
        "super refers to:",
        "Parent class",
        "Object",
        "Loop",
        "None",
        1,
        "Advanced",
    ),
    (
        "Module scope prevents:",
        "Global pollution",
        "Errors",
        "Loops",
        "Objects",
        1,
        "Advanced",
    ),
    (
        "Memoization improves:",
        "Performance",
        "Memory leak",
        "Looping",
        "None",
        1,
        "Advanced",
    ),
    (
        "Garbage collection removes:",
        "Unused memory",
        "Functions",
        "Loops",
        "Classes",
        1,
        "Advanced",
    ),
    (
        "Strict mode enabled by:",
        '"use strict"',
        '"strict mode"',
        "enable strict",
        "start strict",
        1,
        "Advanced",
    ),
]

# Clear existing questions for this quiz
js_job_quiz.questions.all().delete()

# Add questions
for q_data in questions_data:
    q = question.objects.create(quiz=js_job_quiz, text=q_data[0], level=q_data[6])

    # Create choices
    choices_data = [
        (q_data[1], 1 == q_data[5]),
        (q_data[2], 2 == q_data[5]),
        (q_data[3], 3 == q_data[5]),
        (q_data[4], 4 == q_data[5]),
    ]

    for i, (choice_text, is_correct) in enumerate(choices_data, 1):
        choice.objects.create(question=q, text=choice_text, is_correct=is_correct)

print(f"Added {len(questions_data)} questions to JavaScript Job Test")
print(
    f"Beginner: {question.objects.filter(quiz=js_job_quiz, level='Beginner').count()}"
)
print(
    f"Intermediate: {question.objects.filter(quiz=js_job_quiz, level='Intermediate').count()}"
)
print(
    f"Advanced: {question.objects.filter(quiz=js_job_quiz, level='Advanced').count()}"
)
