# Generated by Django 6.0.3 on 2026-04-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_attempt_student_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_answer',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='student_answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='student_answer',
            name='selected_choice',
        ),
        migrations.DeleteModel(
            name='attempt',
        ),
        migrations.DeleteModel(
            name='student_answer',
        ),
    ]
